name: newsletter-suioip

services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    image: suioip/newsletter-app:local
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:delegated
    environment:
      - APP_ENV=local
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks: [suioip]

  webserver:
    image: nginx:1.27-alpine
    ports:
      - "${APP_PORT:-8080}:80"
    volumes:
      - .:/var/www/html:delegated
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks: [suioip]

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_DATABASE:-newsletter_suioip}
      POSTGRES_USER: ${DB_USERNAME:-suioip}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - suioip-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-suioip}"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks: [suioip]

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    networks: [suioip]

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - "8025:8025"   # UI web
      - "1025:1025"   # SMTP
    networks: [suioip]

  openldap:
    image: osixia/openldap:1.5.0
    environment:
      LDAP_ORGANISATION: "Suioip"
      LDAP_DOMAIN: "example.org"
      LDAP_ADMIN_PASSWORD: "admin"
    ports:
      - "389:389"
    networks: [suioip]
    profiles: ["ldap"]

networks:
  suioip:
    driver: bridge

volumes:
  suioip-postgres-data:
